# Generated by Django 2.2.13 on 2021-01-25 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_view', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Author',
            new_name='AuthorPost',
        ),
    ]
