# Generated by Django 2.2.13 on 2021-01-24 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_articlepost_total_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlepost',
            name='href',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='articlepost',
            name='href_title',
            field=models.CharField(default='', max_length=100),
        ),
    ]
